### ISSUE TITLE
Cannot read properties of undefined (reading 'mat4')

### ISSUE THREAD

**Issue by bergonom** [acamposuribe/p5.brush#29]
I just tried adding p5.brush to my simple local app and I am getting this error.
I have tried a couple different ways of installing the library, but currently I am
loading both p5 and p5.brush from the CDN [as you do in your example](https://github.com/acamposuribe/p5.brush/blob/main/example/index.html).
I'm not actually trying to use it yet, so far I have only added the script tags to my HTML.

```
    <script src="https://cdn.jsdelivr.net/npm/p5@1.9.0/lib/p5.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/p5.brush@latest/dist/p5.brush.js"></script>
```
Any ideas what I might be doing wrong?

```
TypeError: Cannot read properties of undefined (reading 'mat4')
    at Object.trans (p5.brush.js:1:2886)
    at w (p5.brush.js:1:13356)
    at Object.blend (p5.brush.js:1:4021)
    at p5.brush.js:1:13503
    at p5.callRegisteredHooksFor (p5.js:63189:30)
    at _setup (p5.js:63354:21)
    at _runIfPreloadsAreDone (p5.js:63265:27)
    at p5._decrementPreload (p5.js:63276:25)
    at img.onload (p5.js:84272:22)
trans @ p5.brush.js:1
w @ p5.brush.js:1
blend @ p5.brush.js:1
(anonymous) @ p5.brush.js:1
p5.callRegisteredHooksFor @ p5.js:63189
_setup @ p5.js:63354
_runIfPreloadsAreDone @ p5.js:63265
_decrementPreload @ p5.js:63276
img.onload @ p5.js:84272
load (async)
(anonymous) @ p5.js:84263
Promise.then (async)
_main.default.loadImage @ p5.js:84238
(anonymous) @ p5.js:63288
preload @ imageTracer.js:37
_start @ p5.js:63245
p5 @ p5.js:63573
_globalInit @ p5.js:62472
Promise.then (async)
295.../core/main @ p5.js:62492
o @ p5.js:40
(anonymous) @ p5.js:42
281../accessibility/color_namer @ p5.js:53693
o @ p5.js:40
r @ p5.js:47
(anonymous) @ p5.js:51
(anonymous) @ p5.js:18
(anonymous) @ p5.js:20
```

**Comment by bergonom** [comment]
Oh, also you mentioned the option of using the minified version of p5.brush (`p5.brush.min.js`) but I don't see it in the repo. Is that available somewhere else?

**Comment by bergonom** [comment]
UPDATE: I needed to create my canvas in WebGL mode.
